# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marco/NetBeansProjects/bahiart2023

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marco/NetBeansProjects/bahiart2023

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marco/NetBeansProjects/bahiart2023/CMakeFiles /home/marco/NetBeansProjects/bahiart2023//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marco/NetBeansProjects/bahiart2023/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bahiart

# Build rule for target.
bahiart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bahiart
.PHONY : bahiart

# fast build rule for target.
bahiart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bahiart.dir/build.make CMakeFiles/bahiart.dir/build
.PHONY : bahiart/fast

#=============================================================================
# Target rules for targets named sockets

# Build rule for target.
sockets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sockets
.PHONY : sockets

# fast build rule for target.
sockets/fast:
	$(MAKE) $(MAKESILENT) -f src/network/CMakeFiles/sockets.dir/build.make src/network/CMakeFiles/sockets.dir/build
.PHONY : sockets/fast

#=============================================================================
# Target rules for targets named tcpsocket

# Build rule for target.
tcpsocket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcpsocket
.PHONY : tcpsocket

# fast build rule for target.
tcpsocket/fast:
	$(MAKE) $(MAKESILENT) -f src/network/CMakeFiles/tcpsocket.dir/build.make src/network/CMakeFiles/tcpsocket.dir/build
.PHONY : tcpsocket/fast

#=============================================================================
# Target rules for targets named udpsocket

# Build rule for target.
udpsocket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 udpsocket
.PHONY : udpsocket

# fast build rule for target.
udpsocket/fast:
	$(MAKE) $(MAKESILENT) -f src/network/CMakeFiles/udpsocket.dir/build.make src/network/CMakeFiles/udpsocket.dir/build
.PHONY : udpsocket/fast

tests/networkmodel/testNetworkModel.o: tests/networkmodel/testNetworkModel.cpp.o
.PHONY : tests/networkmodel/testNetworkModel.o

# target to build an object file
tests/networkmodel/testNetworkModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bahiart.dir/build.make CMakeFiles/bahiart.dir/tests/networkmodel/testNetworkModel.cpp.o
.PHONY : tests/networkmodel/testNetworkModel.cpp.o

tests/networkmodel/testNetworkModel.i: tests/networkmodel/testNetworkModel.cpp.i
.PHONY : tests/networkmodel/testNetworkModel.i

# target to preprocess a source file
tests/networkmodel/testNetworkModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bahiart.dir/build.make CMakeFiles/bahiart.dir/tests/networkmodel/testNetworkModel.cpp.i
.PHONY : tests/networkmodel/testNetworkModel.cpp.i

tests/networkmodel/testNetworkModel.s: tests/networkmodel/testNetworkModel.cpp.s
.PHONY : tests/networkmodel/testNetworkModel.s

# target to generate assembly for a file
tests/networkmodel/testNetworkModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bahiart.dir/build.make CMakeFiles/bahiart.dir/tests/networkmodel/testNetworkModel.cpp.s
.PHONY : tests/networkmodel/testNetworkModel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bahiart"
	@echo "... sockets"
	@echo "... tcpsocket"
	@echo "... udpsocket"
	@echo "... tests/networkmodel/testNetworkModel.o"
	@echo "... tests/networkmodel/testNetworkModel.i"
	@echo "... tests/networkmodel/testNetworkModel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

